export const ONE_SEC_IN_MILLISECONDS = 1000;
export const ONE_MIN_IN_MILLISECONDS = ONE_SEC_IN_MILLISECONDS * 60;
export const ONE_HOUR_IN_MILLISECONDS = ONE_MIN_IN_MILLISECONDS * 60;
export const NINE_HOURS_IN_MILLISECONDS = ONE_HOUR_IN_MILLISECONDS * 9;
export const ONE_DAY_IN_MILLISECONDS = ONE_HOUR_IN_MILLISECONDS * 24;
export const ONE_MONTH_IN_MILLISECONDS = ONE_DAY_IN_MILLISECONDS * 30;
